### ISSUE TITLE
Error while using 'lein scss auto'

### ISSUE THREAD

**Issue by murtaza52** [rtircher/lein-haml-sass#2]
Hi,

Thanks for the plugin. I get the following error while executing 'lein scss auto'. Can you help ?

Ready to compile scss files located in resources/scss
LoadError: no such file to load -- haml
  require at org/jruby/RubyKernel.java:1062
  require at file:/Users/murtaza/.m2/repository/org/jruby/jruby-complete/1.6.8/jruby-complete-1.6.8.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36
   (root) at <script>:1
org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- haml
    at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:136)
    at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1263)
    at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1256)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
    at leiningen.lein_haml_sass.render_engine$ensure_engine_started_BANG_$fn__1386.invoke(render_engine.clj:44)
    at clojure.lang.AFn.call(AFn.java:18)
    at clojure.lang.LockingTransaction.run(LockingTransaction.java:263)
    at clojure.lang.LockingTransaction.runInTransaction(LockingTransaction.java:231)
    at leiningen.lein_haml_sass.render_engine$ensure_engine_started_BANG_.invoke(render_engine.clj:41)
    at leiningen.lein_haml_sass.render_engine$render_all_BANG_.invoke(render_engine.clj:83)
    at leiningen.lein_haml_sass.render_engine$render_all_BANG_.invoke(render_engine.clj:80)
    at leiningen.tasks$auto.invoke(tasks.clj:24)
    at leiningen.scss$scss.doInvoke(scss.clj:9)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:619)
    at leiningen.core.main$resolve_task$fn__3029.doInvoke(main.clj:189)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at leiningen.core.main$apply_task.invoke(main.clj:230)
    at leiningen.core.main$resolve_and_apply.invoke(main.clj:234)
    at leiningen.core.main$_main$fn__3092.invoke(main.clj:303)
    at leiningen.core.main$_main.doInvoke(main.clj:290)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:617)
    at clojure.main$main_opt.invoke(main.clj:335)
    at clojure.main$main.doInvoke(main.clj:440)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at clojure.lang.Var.invoke(Var.java:427)
    at clojure.lang.AFn.applyToHelper(AFn.java:172)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- haml

**Comment by rtircher** [comment]
Can you try again with this version:
[lein-haml-sass "0.2.7-SNAPSHOT"]

It looks like it was not downloading sass.

**Comment by hammerdr** [comment]
Renaud,

The URL was updated only in the project.clj, it needs to be updated in tasks, too. https://github.com/rtircher/lein-haml-sass/blob/master/src/leiningen/tasks.clj

**Comment by rtircher** [comment]
thanks

**Comment by murtaza52** [comment]
Hi Renaud,

Thanks, that solved the issue.

One nitpik - If I have a file named main.scss it is compiled to main.

So to get main.css I have to name my file main.css.scss.

Will it not be more convenient to append .css to the file name after the
compilation is done ?

Thanks,
Murtaza

**Comment by rtircher** [comment]
To solve this issue you can add :output-extension “css” to your scss map in your project.clj.

The scss map would look something like:
:scss {
  :src "resources/scss"
  :output-directory "resources/public/css"
  :output-extension "css"
}

I guess I could make this append automatic if I detect there is no extension to your file.

Renaud
